backend:
  name: git-gateway
  branch: main
  # 非常重要：強制指定 Identity 服務的原始網域
  site_domain: radiant-swan-9d56af.netlify.app

# 您的官方自定義網址
site_url: https://1page.chan-far.com

media_folder: "images"
public_folder: "/images"

collections:
  - name: "content"
    label: "網站內容"
    delete: false
    files:
      - label: "最新消息清單"
        name: "news_list"
        file: "news.json"
        fields:
          - label: "最新消息"
            name: "news"
            widget: "list"
            fields:
              - { label: "日期", name: "date", widget: "datetime", format: "YYYY-MM-DD", timeFormat: false }
              - { label: "標題", name: "title", widget: "string" }
              - { label: "內容", name: "content", widget: "markdown" }
